--employees 에서 전체 내용 조회
SELECT
	*
FROM
	EMPLOYEES e ;
	
--first_name, last_name, job_id 조회
SELECT
	FIRST_NAME,
	last_name,
	job_id
FROM
	EMPLOYEES e ;
	
--사원번호가 176인 사람의 LAST_NAME 과 DEPARTMENT_ID 조회
SELECT LAST_NAME, DEPARTMENT_ID  FROM EMPLOYEES WHERE EMPLOYEE_ID=176;

--연봉이 12000 이상 되는 직원들의 LAST_NAME과 SALARY 조회
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY >= 12000;

--연봉이 5000에서 12000의 범위 이외인 사람들의 LAST_NAME과 SALARY 조회
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY>12000 OR SALARY<5000;

--부서번호가 20, 50 부서에서 근무하는 사원들의 LAST_NAME, DEPARTMENT_ID 조회
SELECT LAST_NAME, DEPARTMENT_ID  FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20,50) ;

--부서번호가 20, 50 부서에서 근무하는 사원들의 LAST_NAME, DEPARTMENT_ID 오름차순 조회
SELECT LAST_NAME, DEPARTMENT_ID  FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20,50) ORDER BY LAST_NAME , DEPARTMENT_ID ;

--커미션을 버는 모든 사원들의 LAST_NAME, SALARY, COMMISSION_PCT 조회
SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT>0 ORDER BY SALARY DESC, COMMISSION_PCT DESC;

--SALARY가 2500,3500,7000이 아니며 JOB_ID이 SA_REP 나 ST_CLERK인 사원 조회
SELECT * FROM EMPLOYEES WHERE SALARY NOT IN(2500,3000,7000) AND JOB_ID IN('SA_REP','ST_CLERK');

--2017-01-01 ~ 2017-12-31 사이에 고용도니 사원들의 LAST_NAME, EMPLOYEE_ID, HIRE_DATE 조회
--HIRE_DATE 내림차순 정렬
SELECT LAST_NAME, EMPLOYEE_ID , HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE >='2017-01-01' AND HIRE_DATE <='2017-12-31' ORDER BY HIRE_DATE DESC; 

--BETWEEN A AND B
--부서번호가 20, 50 부서에서 근무하고, 연봉이 5000 ~ 12000 사이인 사원들의 LAST_NAME, SALARY 조회
--SALARY 오름차순
SELECT LAST_NAME, SALARY 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN(20,50) AND SALARY BETWEEN 5000 AND 12000
ORDER BY SALARY ;


--2017-01-01 ~ 2017-12-31 사이에 고용된 사원들의 LAST_NAME,EMPLOYEE_ID, HIRE_DATE 조회
--HIRE_DATE 내림차순 정렬
SELECT LAST_NAME, EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES 
WHERE HIRE_DATE BETWEEN '2017-01-01' AND '2017-12-31' 
ORDER BY HIRE_DATE DESC;

--연봉이 5000에서 12000의 범위 이외인 사람들의 LAST_NAME과 SALARY 조회
SELECT LAST_NAME, SALARY 
FROM EMPLOYEES 
WHERE SALARY NOT BETWEEN 5000 AND 12000;